repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        exclude: >
            (?x)^(
                .*\.css|
                .*\.js|
                \.tox
            )$
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.265
    hooks:
      - id: ruff
        exclude: >
          (?x)^(
              .*\.jinja.py|
          )$

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ["--config", "pyproject.toml", "--target-version", "py310"]
        exclude: >
          (?x)^(
              .*\.jinja.py|
          )$


  - repo: https://github.com/PyCQA/docformatter
    rev: v1.6.5
    hooks:
      - id: docformatter

  - repo: https://github.com/nrbnlulu/qt-pre-commit-hooks
    rev: v0.1.5
    hooks:
      -  id: qml-format
